version: '3'

networks:
  pkmn-network:
    driver: bridge

services:

  #
  # Project
  #

  pkmn-optimiser:
    container_name: pkmn-optimiser
    build:
      context: ./docker
      dockerfile: ./Dockerfile-dev
    environment:
      - DEBUG=pkmn:*
      - NODE_ENV=development
      - PG_HOST
      - PG_PORT
      - PG_USERNAME
      - PG_PASSWORD
      - PG_DATABASE
    ports:
      - "3000:3000"
    networks:
       - pkmn-network
    volumes:
      - .:/app
      - ./modules:/modules

  #
  # Dev Services
  #

  pkmn-db:
    container_name: pkmn-db
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
      args:
        - PG_HOST
        - PG_PORT
        - PG_USERNAME
        - PG_PASSWORD
        - PG_DATABASE
    ports:
      - "5432:5432"
    networks:
      - pkmn-network
    volumes:
      - ./.env:/var/.env

  redis-master:
    image: redis:3
    ports:
      - "6379:6379"
    networks:
      - pkmn-network

  redis-slave:
    image: redis:3
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379
    networks:
      - pkmn-network
